services:
  app:
    container_name: freelancer-app
    depends_on:
      - postgres
    image: neren3/freelancer-marketplace:latest
    environment:
      - DB_HOST=postgres
    ports:
      - "8080:8080"

  postgres:
    container_name: pg_local
    image: postgres:17.2-alpine
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=freelance
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: