services:
  app:
    container_name: freelancer-app
    depends_on:
      - postgres
    image: neren3/freelancer-marketplace:latest
    environment:
      - DB_HOST=postgres
      - MQ_HOST=rabbitmq
    ports:
      - "8080:8080"

  postgres:
    container_name: pg_local
    image: postgres:17.2-alpine
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=freelance
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    container_name: rabbit_local
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_PASS=secret
      - RABBITMQ_DEFAULT_USER=myuser
    ports:
      - "5672:5672"
volumes:
  postgres_data: